//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IClient {

    /**
     * @return OK
     */
    achievementsAll(): Promise<AchievementResponse[]>;

    /**
     * @param body (optional) 
     * @return OK
     */
    achievementsPOST(body: AchievementPostRequest | undefined): Promise<AchievementResponse>;

    /**
     * @return OK
     */
    achievementsGET(id: number): Promise<AchievementResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    achievementsPATCH(id: number, body: AchievementPatchRequest | undefined): Promise<AchievementResponse>;

    /**
     * @return OK
     */
    achievementsDELETE(id: number): Promise<void>;

    /**
     * @return OK
     */
    affiliatesAll(): Promise<AffiliateResponse[]>;

    /**
     * @param body (optional) 
     * @return OK
     */
    affiliatesPOST(body: AffiliatePostRequest | undefined): Promise<AffiliateResponse>;

    /**
     * @return OK
     */
    affiliatesGET(id: number): Promise<AffiliateResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    affiliatesPATCH(id: number, body: AffiliatePatchRequest | undefined): Promise<AffiliateResponse>;

    /**
     * @return OK
     */
    affiliatesDELETE(id: number): Promise<void>;

    /**
     * @param body (optional) 
     * @return OK
     */
    login(body: LoginRequest | undefined): Promise<void>;

    /**
     * @param body (optional) 
     * @return OK
     */
    register(body: UsersPostRequest | undefined): Promise<void>;

    /**
     * @return OK
     */
    contactSettingsGET(): Promise<ContactSettingsResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    contactSettingsPATCH(body: ContactSettingsPatchRequest | undefined): Promise<ContactSettingsResponse>;

    /**
     * @return OK
     */
    coreValuesAll(): Promise<CoreValuesResponse[]>;

    /**
     * @param body (optional) 
     * @return OK
     */
    coreValuesPOST(body: CoreValuesPostRequest | undefined): Promise<CoreValuesResponse>;

    /**
     * @return OK
     */
    coreValuesGET(id: number): Promise<CoreValuesResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    coreValuesPATCH(id: number, body: CoreValuesPatchRequest | undefined): Promise<CoreValuesResponse>;

    /**
     * @return OK
     */
    coreValuesDELETE(id: number): Promise<void>;

    /**
     * @return OK
     */
    missionVisionGET(): Promise<MissionVisionResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    missionVisionPATCH(body: MissionVisionPatchRequest | undefined): Promise<MissionVisionResponse>;

    /**
     * @return OK
     */
    oCRCEventDetailsGET(): Promise<OCRCEventDetailsResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCEventDetailsPATCH(body: OCRCEventDetailsPatchRequest | undefined): Promise<OCRCEventDetailsResponse>;

    /**
     * @return OK
     */
    oCRCEventHighlightsAll(): Promise<OCRCEventHighlightsResponse[]>;

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCEventHighlightsPOST(body: OCRCEventHighlightsPostRequest | undefined): Promise<OCRCEventHighlightsResponse>;

    /**
     * @return OK
     */
    oCRCEventHighlightsGET(id: number): Promise<OCRCEventHighlightsResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCEventHighlightsPATCH(id: number, body: OCRCEventHighlightsPatchRequest | undefined): Promise<OCRCEventHighlightsResponse>;

    /**
     * @return OK
     */
    oCRCEventHighlightsDELETE(id: number): Promise<void>;

    /**
     * @return OK
     */
    oCRCTimelinesAll(): Promise<OCRCTimelineResponse[]>;

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCTimelinesPOST(body: OCRCTimelinePostRequest | undefined): Promise<OCRCTimelineResponse>;

    /**
     * @return OK
     */
    oCRCTimelinesGET(id: number): Promise<OCRCTimelineResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCTimelinesPATCH(id: number, body: OCRCTimelinePatchRequest | undefined): Promise<OCRCTimelineResponse>;

    /**
     * @return OK
     */
    oCRCTimelinesDELETE(id: number): Promise<void>;

    /**
     * @return OK
     */
    servicesAll(): Promise<ServiceResponse[]>;

    /**
     * @param body (optional) 
     * @return OK
     */
    servicesPOST(body: ServicePostRequest | undefined): Promise<ServiceResponse>;

    /**
     * @return OK
     */
    servicesGET(id: number): Promise<ServiceResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    servicesPATCH(id: number, body: ServicePatchRequest | undefined): Promise<ServiceResponse>;

    /**
     * @return OK
     */
    servicesDELETE(id: number): Promise<void>;

    /**
     * @return OK
     */
    teamMembersAll(): Promise<TeamMembersResponse[]>;

    /**
     * @param body (optional) 
     * @return OK
     */
    teamMembersPOST(body: TeamMembersPostRequest | undefined): Promise<TeamMembersResponse>;

    /**
     * @return OK
     */
    teamMembersGET(id: number): Promise<TeamMembersResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    teamMembersPATCH(id: number, body: TeamMembersPatchRequest | undefined): Promise<TeamMembersResponse>;

    /**
     * @return OK
     */
    teamMembersDELETE(id: number): Promise<void>;

    /**
     * @return OK
     */
    testimonialsAll(): Promise<TestimonialResponse[]>;

    /**
     * @param body (optional) 
     * @return OK
     */
    testimonialsPOST(body: TestimonialPostRequest | undefined): Promise<TestimonialResponse>;

    /**
     * @return OK
     */
    testimonialsGET(id: number): Promise<TestimonialResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    testimonialsPATCH(id: number, body: TestimonialPatchRequest | undefined): Promise<TestimonialResponse>;

    /**
     * @return OK
     */
    testimonialsDELETE(id: number): Promise<void>;
}

export class Client implements IClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    achievementsAll(): Promise<AchievementResponse[]> {
        let url_ = this.baseUrl + "/api/Achievements";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAchievementsAll(_response);
        });
    }

    protected processAchievementsAll(response: Response): Promise<AchievementResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AchievementResponse[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AchievementResponse[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    achievementsPOST(body: AchievementPostRequest | undefined): Promise<AchievementResponse> {
        let url_ = this.baseUrl + "/api/Achievements";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAchievementsPOST(_response);
        });
    }

    protected processAchievementsPOST(response: Response): Promise<AchievementResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AchievementResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AchievementResponse>(null as any);
    }

    /**
     * @return OK
     */
    achievementsGET(id: number): Promise<AchievementResponse> {
        let url_ = this.baseUrl + "/api/Achievements/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAchievementsGET(_response);
        });
    }

    protected processAchievementsGET(response: Response): Promise<AchievementResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AchievementResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AchievementResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    achievementsPATCH(id: number, body: AchievementPatchRequest | undefined): Promise<AchievementResponse> {
        let url_ = this.baseUrl + "/api/Achievements/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAchievementsPATCH(_response);
        });
    }

    protected processAchievementsPATCH(response: Response): Promise<AchievementResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AchievementResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AchievementResponse>(null as any);
    }

    /**
     * @return OK
     */
    achievementsDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Achievements/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAchievementsDELETE(_response);
        });
    }

    protected processAchievementsDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    affiliatesAll(): Promise<AffiliateResponse[]> {
        let url_ = this.baseUrl + "/api/Affiliates";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAffiliatesAll(_response);
        });
    }

    protected processAffiliatesAll(response: Response): Promise<AffiliateResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AffiliateResponse[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AffiliateResponse[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    affiliatesPOST(body: AffiliatePostRequest | undefined): Promise<AffiliateResponse> {
        let url_ = this.baseUrl + "/api/Affiliates";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAffiliatesPOST(_response);
        });
    }

    protected processAffiliatesPOST(response: Response): Promise<AffiliateResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AffiliateResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AffiliateResponse>(null as any);
    }

    /**
     * @return OK
     */
    affiliatesGET(id: number): Promise<AffiliateResponse> {
        let url_ = this.baseUrl + "/api/Affiliates/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAffiliatesGET(_response);
        });
    }

    protected processAffiliatesGET(response: Response): Promise<AffiliateResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AffiliateResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AffiliateResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    affiliatesPATCH(id: number, body: AffiliatePatchRequest | undefined): Promise<AffiliateResponse> {
        let url_ = this.baseUrl + "/api/Affiliates/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAffiliatesPATCH(_response);
        });
    }

    protected processAffiliatesPATCH(response: Response): Promise<AffiliateResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AffiliateResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AffiliateResponse>(null as any);
    }

    /**
     * @return OK
     */
    affiliatesDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Affiliates/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAffiliatesDELETE(_response);
        });
    }

    protected processAffiliatesDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    login(body: LoginRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    register(body: UsersPostRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Auth/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    contactSettingsGET(): Promise<ContactSettingsResponse> {
        let url_ = this.baseUrl + "/api/ContactSettings";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processContactSettingsGET(_response);
        });
    }

    protected processContactSettingsGET(response: Response): Promise<ContactSettingsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ContactSettingsResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ContactSettingsResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    contactSettingsPATCH(body: ContactSettingsPatchRequest | undefined): Promise<ContactSettingsResponse> {
        let url_ = this.baseUrl + "/api/ContactSettings";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processContactSettingsPATCH(_response);
        });
    }

    protected processContactSettingsPATCH(response: Response): Promise<ContactSettingsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ContactSettingsResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ContactSettingsResponse>(null as any);
    }

    /**
     * @return OK
     */
    coreValuesAll(): Promise<CoreValuesResponse[]> {
        let url_ = this.baseUrl + "/api/CoreValues";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCoreValuesAll(_response);
        });
    }

    protected processCoreValuesAll(response: Response): Promise<CoreValuesResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CoreValuesResponse[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CoreValuesResponse[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    coreValuesPOST(body: CoreValuesPostRequest | undefined): Promise<CoreValuesResponse> {
        let url_ = this.baseUrl + "/api/CoreValues";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCoreValuesPOST(_response);
        });
    }

    protected processCoreValuesPOST(response: Response): Promise<CoreValuesResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CoreValuesResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CoreValuesResponse>(null as any);
    }

    /**
     * @return OK
     */
    coreValuesGET(id: number): Promise<CoreValuesResponse> {
        let url_ = this.baseUrl + "/api/CoreValues/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCoreValuesGET(_response);
        });
    }

    protected processCoreValuesGET(response: Response): Promise<CoreValuesResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CoreValuesResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CoreValuesResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    coreValuesPATCH(id: number, body: CoreValuesPatchRequest | undefined): Promise<CoreValuesResponse> {
        let url_ = this.baseUrl + "/api/CoreValues/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCoreValuesPATCH(_response);
        });
    }

    protected processCoreValuesPATCH(response: Response): Promise<CoreValuesResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CoreValuesResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CoreValuesResponse>(null as any);
    }

    /**
     * @return OK
     */
    coreValuesDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/CoreValues/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCoreValuesDELETE(_response);
        });
    }

    protected processCoreValuesDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    missionVisionGET(): Promise<MissionVisionResponse> {
        let url_ = this.baseUrl + "/api/MissionVision";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMissionVisionGET(_response);
        });
    }

    protected processMissionVisionGET(response: Response): Promise<MissionVisionResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MissionVisionResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MissionVisionResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    missionVisionPATCH(body: MissionVisionPatchRequest | undefined): Promise<MissionVisionResponse> {
        let url_ = this.baseUrl + "/api/MissionVision";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMissionVisionPATCH(_response);
        });
    }

    protected processMissionVisionPATCH(response: Response): Promise<MissionVisionResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MissionVisionResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MissionVisionResponse>(null as any);
    }

    /**
     * @return OK
     */
    oCRCEventDetailsGET(): Promise<OCRCEventDetailsResponse> {
        let url_ = this.baseUrl + "/api/OCRCEventDetails";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventDetailsGET(_response);
        });
    }

    protected processOCRCEventDetailsGET(response: Response): Promise<OCRCEventDetailsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as OCRCEventDetailsResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OCRCEventDetailsResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCEventDetailsPATCH(body: OCRCEventDetailsPatchRequest | undefined): Promise<OCRCEventDetailsResponse> {
        let url_ = this.baseUrl + "/api/OCRCEventDetails";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventDetailsPATCH(_response);
        });
    }

    protected processOCRCEventDetailsPATCH(response: Response): Promise<OCRCEventDetailsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as OCRCEventDetailsResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OCRCEventDetailsResponse>(null as any);
    }

    /**
     * @return OK
     */
    oCRCEventHighlightsAll(): Promise<OCRCEventHighlightsResponse[]> {
        let url_ = this.baseUrl + "/api/OCRCEventHighlights";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventHighlightsAll(_response);
        });
    }

    protected processOCRCEventHighlightsAll(response: Response): Promise<OCRCEventHighlightsResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as OCRCEventHighlightsResponse[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OCRCEventHighlightsResponse[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCEventHighlightsPOST(body: OCRCEventHighlightsPostRequest | undefined): Promise<OCRCEventHighlightsResponse> {
        let url_ = this.baseUrl + "/api/OCRCEventHighlights";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventHighlightsPOST(_response);
        });
    }

    protected processOCRCEventHighlightsPOST(response: Response): Promise<OCRCEventHighlightsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as OCRCEventHighlightsResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OCRCEventHighlightsResponse>(null as any);
    }

    /**
     * @return OK
     */
    oCRCEventHighlightsGET(id: number): Promise<OCRCEventHighlightsResponse> {
        let url_ = this.baseUrl + "/api/OCRCEventHighlights/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventHighlightsGET(_response);
        });
    }

    protected processOCRCEventHighlightsGET(response: Response): Promise<OCRCEventHighlightsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as OCRCEventHighlightsResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OCRCEventHighlightsResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCEventHighlightsPATCH(id: number, body: OCRCEventHighlightsPatchRequest | undefined): Promise<OCRCEventHighlightsResponse> {
        let url_ = this.baseUrl + "/api/OCRCEventHighlights/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventHighlightsPATCH(_response);
        });
    }

    protected processOCRCEventHighlightsPATCH(response: Response): Promise<OCRCEventHighlightsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as OCRCEventHighlightsResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OCRCEventHighlightsResponse>(null as any);
    }

    /**
     * @return OK
     */
    oCRCEventHighlightsDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCEventHighlights/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventHighlightsDELETE(_response);
        });
    }

    protected processOCRCEventHighlightsDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    oCRCTimelinesAll(): Promise<OCRCTimelineResponse[]> {
        let url_ = this.baseUrl + "/api/OCRCTimelines";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCTimelinesAll(_response);
        });
    }

    protected processOCRCTimelinesAll(response: Response): Promise<OCRCTimelineResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as OCRCTimelineResponse[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OCRCTimelineResponse[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCTimelinesPOST(body: OCRCTimelinePostRequest | undefined): Promise<OCRCTimelineResponse> {
        let url_ = this.baseUrl + "/api/OCRCTimelines";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCTimelinesPOST(_response);
        });
    }

    protected processOCRCTimelinesPOST(response: Response): Promise<OCRCTimelineResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as OCRCTimelineResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OCRCTimelineResponse>(null as any);
    }

    /**
     * @return OK
     */
    oCRCTimelinesGET(id: number): Promise<OCRCTimelineResponse> {
        let url_ = this.baseUrl + "/api/OCRCTimelines/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCTimelinesGET(_response);
        });
    }

    protected processOCRCTimelinesGET(response: Response): Promise<OCRCTimelineResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as OCRCTimelineResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OCRCTimelineResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCTimelinesPATCH(id: number, body: OCRCTimelinePatchRequest | undefined): Promise<OCRCTimelineResponse> {
        let url_ = this.baseUrl + "/api/OCRCTimelines/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCTimelinesPATCH(_response);
        });
    }

    protected processOCRCTimelinesPATCH(response: Response): Promise<OCRCTimelineResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as OCRCTimelineResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OCRCTimelineResponse>(null as any);
    }

    /**
     * @return OK
     */
    oCRCTimelinesDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCTimelines/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCTimelinesDELETE(_response);
        });
    }

    protected processOCRCTimelinesDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    servicesAll(): Promise<ServiceResponse[]> {
        let url_ = this.baseUrl + "/api/Services";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesAll(_response);
        });
    }

    protected processServicesAll(response: Response): Promise<ServiceResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ServiceResponse[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ServiceResponse[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    servicesPOST(body: ServicePostRequest | undefined): Promise<ServiceResponse> {
        let url_ = this.baseUrl + "/api/Services";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesPOST(_response);
        });
    }

    protected processServicesPOST(response: Response): Promise<ServiceResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ServiceResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ServiceResponse>(null as any);
    }

    /**
     * @return OK
     */
    servicesGET(id: number): Promise<ServiceResponse> {
        let url_ = this.baseUrl + "/api/Services/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesGET(_response);
        });
    }

    protected processServicesGET(response: Response): Promise<ServiceResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ServiceResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ServiceResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    servicesPATCH(id: number, body: ServicePatchRequest | undefined): Promise<ServiceResponse> {
        let url_ = this.baseUrl + "/api/Services/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesPATCH(_response);
        });
    }

    protected processServicesPATCH(response: Response): Promise<ServiceResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ServiceResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ServiceResponse>(null as any);
    }

    /**
     * @return OK
     */
    servicesDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Services/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesDELETE(_response);
        });
    }

    protected processServicesDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    teamMembersAll(): Promise<TeamMembersResponse[]> {
        let url_ = this.baseUrl + "/api/TeamMembers";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTeamMembersAll(_response);
        });
    }

    protected processTeamMembersAll(response: Response): Promise<TeamMembersResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TeamMembersResponse[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TeamMembersResponse[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    teamMembersPOST(body: TeamMembersPostRequest | undefined): Promise<TeamMembersResponse> {
        let url_ = this.baseUrl + "/api/TeamMembers";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTeamMembersPOST(_response);
        });
    }

    protected processTeamMembersPOST(response: Response): Promise<TeamMembersResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TeamMembersResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TeamMembersResponse>(null as any);
    }

    /**
     * @return OK
     */
    teamMembersGET(id: number): Promise<TeamMembersResponse> {
        let url_ = this.baseUrl + "/api/TeamMembers/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTeamMembersGET(_response);
        });
    }

    protected processTeamMembersGET(response: Response): Promise<TeamMembersResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TeamMembersResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TeamMembersResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    teamMembersPATCH(id: number, body: TeamMembersPatchRequest | undefined): Promise<TeamMembersResponse> {
        let url_ = this.baseUrl + "/api/TeamMembers/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTeamMembersPATCH(_response);
        });
    }

    protected processTeamMembersPATCH(response: Response): Promise<TeamMembersResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TeamMembersResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TeamMembersResponse>(null as any);
    }

    /**
     * @return OK
     */
    teamMembersDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/TeamMembers/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTeamMembersDELETE(_response);
        });
    }

    protected processTeamMembersDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    testimonialsAll(): Promise<TestimonialResponse[]> {
        let url_ = this.baseUrl + "/api/Testimonials";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTestimonialsAll(_response);
        });
    }

    protected processTestimonialsAll(response: Response): Promise<TestimonialResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TestimonialResponse[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TestimonialResponse[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    testimonialsPOST(body: TestimonialPostRequest | undefined): Promise<TestimonialResponse> {
        let url_ = this.baseUrl + "/api/Testimonials";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTestimonialsPOST(_response);
        });
    }

    protected processTestimonialsPOST(response: Response): Promise<TestimonialResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TestimonialResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TestimonialResponse>(null as any);
    }

    /**
     * @return OK
     */
    testimonialsGET(id: number): Promise<TestimonialResponse> {
        let url_ = this.baseUrl + "/api/Testimonials/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTestimonialsGET(_response);
        });
    }

    protected processTestimonialsGET(response: Response): Promise<TestimonialResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TestimonialResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TestimonialResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    testimonialsPATCH(id: number, body: TestimonialPatchRequest | undefined): Promise<TestimonialResponse> {
        let url_ = this.baseUrl + "/api/Testimonials/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTestimonialsPATCH(_response);
        });
    }

    protected processTestimonialsPATCH(response: Response): Promise<TestimonialResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TestimonialResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TestimonialResponse>(null as any);
    }

    /**
     * @return OK
     */
    testimonialsDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Testimonials/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTestimonialsDELETE(_response);
        });
    }

    protected processTestimonialsDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface AchievementPatchRequest {
    id: number;
    title: string;
    achievementYear?: number;
    description: string;
    imageUrl: string;
    achivementType?: number;
    displayOrder?: number;
}

export interface AchievementPostRequest {
    title: string;
    achievementYear?: number;
    description: string;
    imageUrl: string;
    achivementType?: number;
    displayOrder?: number;
}

export interface AchievementResponse {
    id?: number;
    title: string;
    achievementYear?: number;
    description: string;
    imageUrl: string;
    achivementType?: number;
    displayOrder?: number;
}

export interface AffiliatePatchRequest {
    id: number;
    name: string;
    logoImageUrl: string;
    websiteUrl: string;
    affiliateType?: number;
    displayOrder?: number;
    isActive?: boolean;
}

export interface AffiliatePostRequest {
    name: string;
    logoImageUrl: string;
    websiteUrl: string;
    affiliateType?: number;
    displayOrder?: number;
    isActive?: boolean;
}

export interface AffiliateResponse {
    id?: number;
    name: string;
    logoImageUrl: string;
    websiteUrl: string;
    affiliateType?: number;
    displayOrder?: number;
    isActive?: boolean;
}

export interface ContactSettingsPatchRequest {
    id: number;
    contactPhone: string;
    contactEmail: string;
    physicalAddress: string;
    businessHours: string;
}

export interface ContactSettingsResponse {
    id?: number;
    contactPhone: string;
    contactEmail: string;
    physicalAddress: string;
    businessHours: string;
}

export interface CoreValuesPatchRequest {
    id: number;
    iconName: string;
    title: string;
    description: string;
    displayOrder?: number;
}

export interface CoreValuesPostRequest {
    iconName: string;
    title: string;
    description: string;
    displayOrder?: number;
}

export interface CoreValuesResponse {
    id?: number;
    iconName: string;
    title: string;
    description: string;
    displayOrder?: number;
}

export interface LoginRequest {
    email: string;
    password: string;
}

export interface MissionVisionPatchRequest {
    id: number;
    missionStatement: string;
    visionStatement: string;
}

export interface MissionVisionResponse {
    id?: number;
    missionStatement: string;
    visionStatement: string;
}

export interface OCRCEventDetailsPatchRequest {
    id: number;
    eventDate?: Date;
    eventTime: string;
    venueName: string;
    eligibility: string;
    rulesPdfUrl: string;
}

export interface OCRCEventDetailsResponse {
    id?: number;
    eventDate?: Date;
    eventTime: string;
    venueName: string;
    eligibility: string;
    rulesPdfUrl: string;
}

export interface OCRCEventHighlightsPatchRequest {
    id: number;
    title: string;
    eventYear?: number;
    description: string;
    imageUrl: string;
    displayOrder?: number;
}

export interface OCRCEventHighlightsPostRequest {
    title: string;
    eventYear?: number;
    description: string;
    imageUrl: string;
    displayOrder?: number;
}

export interface OCRCEventHighlightsResponse {
    id?: number;
    title: string;
    eventYear?: number;
    description: string;
    imageUrl: string;
    displayOrder?: number;
}

export interface OCRCTimelinePatchRequest {
    id?: number;
    timelineYear?: number;
    title: string;
    eventDescription: string;
    displayOrder?: number;
}

export interface OCRCTimelinePostRequest {
    timelineYear?: number;
    title: string;
    eventDescription: string;
    displayOrder?: number;
}

export interface OCRCTimelineResponse {
    id?: number;
    timelineYear?: number;
    title: string;
    eventDescription: string;
    displayOrder?: number;
}

export interface ServicePatchRequest {
    id: number;
    title: string;
    shortDescription: string;
    iconName: string;
    displayOrder?: number;
    isActive?: boolean;
}

export interface ServicePostRequest {
    title: string;
    shortDescription: string;
    iconName: string;
    displayOrder?: number;
    isActive?: boolean;
}

export interface ServiceResponse {
    id?: number;
    title: string;
    shortDescription: string;
    iconName: string;
    displayOrder?: number;
    isActive?: boolean;
}

export interface TeamMembersPatchRequest {
    id: number;
    firstName: string;
    lastName: string;
    roleTitle: string;
    bio: string;
    profileImageUrl: string;
    displayOrder?: number;
    isActive?: boolean;
}

export interface TeamMembersPostRequest {
    firstName: string;
    lastName: string;
    roleTitle: string;
    bio: string;
    profileImageUrl: string;
    displayOrder?: number;
    isActive?: boolean;
}

export interface TeamMembersResponse {
    id?: number;
    firstName: string;
    lastName: string;
    roleTitle: string;
    bio: string;
    profileImageUrl: string;
    displayOrder?: number;
    isActive?: boolean;
}

export interface TestimonialPatchRequest {
    id: number;
    rate: number;
    authorName: string;
    authorRole: string;
    content: string;
    isApproved?: boolean;
}

export interface TestimonialPostRequest {
    rate: number;
    authorName: string;
    authorRole: string;
    content: string;
    isApproved?: boolean;
}

export interface TestimonialResponse {
    id?: number;
    rate?: number;
    authorName: string;
    authorRole: string;
    content: string;
    isApproved?: boolean;
    createdAt?: Date;
}

export interface UsersPostRequest {
    username: string;
    email: string;
    password: string;
    role: string;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}