//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    achievementsGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/Achievements";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAchievementsGET(_response);
        });
    }

    protected processAchievementsGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    achievementsPOST(body: AchievementPostRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Achievements";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAchievementsPOST(_response);
        });
    }

    protected processAchievementsPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    achievementsGET2(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Achievements/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAchievementsGET2(_response);
        });
    }

    protected processAchievementsGET2(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    achievementsPATCH(id: number, body: AchievementPatchRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Achievements/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAchievementsPATCH(_response);
        });
    }

    protected processAchievementsPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    achievementsDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Achievements/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAchievementsDELETE(_response);
        });
    }

    protected processAchievementsDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    affiliatesGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/Affiliates";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAffiliatesGET(_response);
        });
    }

    protected processAffiliatesGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    affiliatesPOST(body: AffiliatePostRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Affiliates";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAffiliatesPOST(_response);
        });
    }

    protected processAffiliatesPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    affiliatesGET2(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Affiliates/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAffiliatesGET2(_response);
        });
    }

    protected processAffiliatesGET2(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    affiliatesPATCH(id: number, body: AffiliatePatchRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Affiliates/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAffiliatesPATCH(_response);
        });
    }

    protected processAffiliatesPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    affiliatesDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Affiliates/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAffiliatesDELETE(_response);
        });
    }

    protected processAffiliatesDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    contactSettingsGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/ContactSettings";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processContactSettingsGET(_response);
        });
    }

    protected processContactSettingsGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    contactSettingsPATCH(body: ContactSettingsPatchRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/ContactSettings";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processContactSettingsPATCH(_response);
        });
    }

    protected processContactSettingsPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    coreValuesGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/CoreValues";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCoreValuesGET(_response);
        });
    }

    protected processCoreValuesGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    coreValuesPOST(body: CoreValuesPostRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/CoreValues";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCoreValuesPOST(_response);
        });
    }

    protected processCoreValuesPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    coreValuesGET2(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/CoreValues/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCoreValuesGET2(_response);
        });
    }

    protected processCoreValuesGET2(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    coreValuesPATCH(id: number, body: CoreValuesPatchRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/CoreValues/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCoreValuesPATCH(_response);
        });
    }

    protected processCoreValuesPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    coreValuesDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/CoreValues/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCoreValuesDELETE(_response);
        });
    }

    protected processCoreValuesDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    missionVisionGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/MissionVision";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMissionVisionGET(_response);
        });
    }

    protected processMissionVisionGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    missionVisionPATCH(body: MissionVisionPatchRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/MissionVision";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMissionVisionPATCH(_response);
        });
    }

    protected processMissionVisionPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    oCRCEventDetailsGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCEventDetails";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventDetailsGET(_response);
        });
    }

    protected processOCRCEventDetailsGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCEventDetailsPATCH(body: OCRCEventDetailsPatchRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCEventDetails";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventDetailsPATCH(_response);
        });
    }

    protected processOCRCEventDetailsPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    oCRCEventHighlightsGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCEventHighlights";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventHighlightsGET(_response);
        });
    }

    protected processOCRCEventHighlightsGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCEventHighlightsPOST(body: OCRCEventHighlightsPostRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCEventHighlights";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventHighlightsPOST(_response);
        });
    }

    protected processOCRCEventHighlightsPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    oCRCEventHighlightsGET2(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCEventHighlights/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventHighlightsGET2(_response);
        });
    }

    protected processOCRCEventHighlightsGET2(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCEventHighlightsPATCH(id: number, body: OCRCEventHighlightsPatchRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCEventHighlights/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventHighlightsPATCH(_response);
        });
    }

    protected processOCRCEventHighlightsPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    oCRCEventHighlightsDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCEventHighlights/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCEventHighlightsDELETE(_response);
        });
    }

    protected processOCRCEventHighlightsDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    oCRCTimelinesGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCTimelines";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCTimelinesGET(_response);
        });
    }

    protected processOCRCTimelinesGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCTimelinesPOST(body: OCRCTimelinePostRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCTimelines";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCTimelinesPOST(_response);
        });
    }

    protected processOCRCTimelinesPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    oCRCTimelinesGET2(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCTimelines/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCTimelinesGET2(_response);
        });
    }

    protected processOCRCTimelinesGET2(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    oCRCTimelinesPATCH(id: number, body: OCRCTimelinePatchRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCTimelines/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCTimelinesPATCH(_response);
        });
    }

    protected processOCRCTimelinesPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    oCRCTimelinesDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/OCRCTimelines/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOCRCTimelinesDELETE(_response);
        });
    }

    protected processOCRCTimelinesDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    servicesGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/Services";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesGET(_response);
        });
    }

    protected processServicesGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    servicesPOST(body: ServicePostRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Services";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesPOST(_response);
        });
    }

    protected processServicesPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    servicesGET2(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Services/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesGET2(_response);
        });
    }

    protected processServicesGET2(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    servicesPATCH(id: number, body: ServicePatchRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Services/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesPATCH(_response);
        });
    }

    protected processServicesPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    servicesDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Services/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesDELETE(_response);
        });
    }

    protected processServicesDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    teamMembersGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/TeamMembers";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTeamMembersGET(_response);
        });
    }

    protected processTeamMembersGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    teamMembersPOST(body: TeamMembersPostRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/TeamMembers";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTeamMembersPOST(_response);
        });
    }

    protected processTeamMembersPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    teamMembersGET2(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/TeamMembers/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTeamMembersGET2(_response);
        });
    }

    protected processTeamMembersGET2(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    teamMembersPATCH(id: number, body: TeamMembersPatchRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/TeamMembers/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTeamMembersPATCH(_response);
        });
    }

    protected processTeamMembersPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    teamMembersDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/TeamMembers/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTeamMembersDELETE(_response);
        });
    }

    protected processTeamMembersDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    testimonialsGET(): Promise<void> {
        let url_ = this.baseUrl + "/api/Testimonials";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTestimonialsGET(_response);
        });
    }

    protected processTestimonialsGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    testimonialsPOST(body: TestimonialPostRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Testimonials";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTestimonialsPOST(_response);
        });
    }

    protected processTestimonialsPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    testimonialsGET2(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Testimonials/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTestimonialsGET2(_response);
        });
    }

    protected processTestimonialsGET2(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    testimonialsPATCH(id: number, body: TestimonialPatchRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Testimonials/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTestimonialsPATCH(_response);
        });
    }

    protected processTestimonialsPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    testimonialsDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Testimonials/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTestimonialsDELETE(_response);
        });
    }

    protected processTestimonialsDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class AchievementPatchRequest implements IAchievementPatchRequest {
    id!: number;
    title!: string;
    achievementYear?: number;
    description!: string;
    imageUrl!: string;
    achivementType?: number;
    displayOrder?: number;

    constructor(data?: IAchievementPatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.achievementYear = _data["achievementYear"];
            this.description = _data["description"];
            this.imageUrl = _data["imageUrl"];
            this.achivementType = _data["achivementType"];
            this.displayOrder = _data["displayOrder"];
        }
    }

    static fromJS(data: any): AchievementPatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AchievementPatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["achievementYear"] = this.achievementYear;
        data["description"] = this.description;
        data["imageUrl"] = this.imageUrl;
        data["achivementType"] = this.achivementType;
        data["displayOrder"] = this.displayOrder;
        return data;
    }
}

export interface IAchievementPatchRequest {
    id: number;
    title: string;
    achievementYear?: number;
    description: string;
    imageUrl: string;
    achivementType?: number;
    displayOrder?: number;
}

export class AchievementPostRequest implements IAchievementPostRequest {
    title!: string;
    achievementYear?: number;
    description!: string;
    imageUrl!: string;
    achivementType?: number;
    displayOrder?: number;

    constructor(data?: IAchievementPostRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.achievementYear = _data["achievementYear"];
            this.description = _data["description"];
            this.imageUrl = _data["imageUrl"];
            this.achivementType = _data["achivementType"];
            this.displayOrder = _data["displayOrder"];
        }
    }

    static fromJS(data: any): AchievementPostRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AchievementPostRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["achievementYear"] = this.achievementYear;
        data["description"] = this.description;
        data["imageUrl"] = this.imageUrl;
        data["achivementType"] = this.achivementType;
        data["displayOrder"] = this.displayOrder;
        return data;
    }
}

export interface IAchievementPostRequest {
    title: string;
    achievementYear?: number;
    description: string;
    imageUrl: string;
    achivementType?: number;
    displayOrder?: number;
}

export class AffiliatePatchRequest implements IAffiliatePatchRequest {
    id!: number;
    name!: string;
    logoImageUrl!: string;
    websiteUrl!: string;
    affiliateType?: number;
    displayOrder?: number;
    isActive?: boolean;

    constructor(data?: IAffiliatePatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.logoImageUrl = _data["logoImageUrl"];
            this.websiteUrl = _data["websiteUrl"];
            this.affiliateType = _data["affiliateType"];
            this.displayOrder = _data["displayOrder"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): AffiliatePatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AffiliatePatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["logoImageUrl"] = this.logoImageUrl;
        data["websiteUrl"] = this.websiteUrl;
        data["affiliateType"] = this.affiliateType;
        data["displayOrder"] = this.displayOrder;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface IAffiliatePatchRequest {
    id: number;
    name: string;
    logoImageUrl: string;
    websiteUrl: string;
    affiliateType?: number;
    displayOrder?: number;
    isActive?: boolean;
}

export class AffiliatePostRequest implements IAffiliatePostRequest {
    name!: string;
    logoImageUrl!: string;
    websiteUrl!: string;
    affiliateType?: number;
    displayOrder?: number;
    isActive?: boolean;

    constructor(data?: IAffiliatePostRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.logoImageUrl = _data["logoImageUrl"];
            this.websiteUrl = _data["websiteUrl"];
            this.affiliateType = _data["affiliateType"];
            this.displayOrder = _data["displayOrder"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): AffiliatePostRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AffiliatePostRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["logoImageUrl"] = this.logoImageUrl;
        data["websiteUrl"] = this.websiteUrl;
        data["affiliateType"] = this.affiliateType;
        data["displayOrder"] = this.displayOrder;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface IAffiliatePostRequest {
    name: string;
    logoImageUrl: string;
    websiteUrl: string;
    affiliateType?: number;
    displayOrder?: number;
    isActive?: boolean;
}

export class ContactSettingsPatchRequest implements IContactSettingsPatchRequest {
    id!: number;
    contactPhone!: string;
    contactEmail!: string;
    physicalAddress!: string;
    businessHours!: string;

    constructor(data?: IContactSettingsPatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.contactPhone = _data["contactPhone"];
            this.contactEmail = _data["contactEmail"];
            this.physicalAddress = _data["physicalAddress"];
            this.businessHours = _data["businessHours"];
        }
    }

    static fromJS(data: any): ContactSettingsPatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ContactSettingsPatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["contactPhone"] = this.contactPhone;
        data["contactEmail"] = this.contactEmail;
        data["physicalAddress"] = this.physicalAddress;
        data["businessHours"] = this.businessHours;
        return data;
    }
}

export interface IContactSettingsPatchRequest {
    id: number;
    contactPhone: string;
    contactEmail: string;
    physicalAddress: string;
    businessHours: string;
}

export class CoreValuesPatchRequest implements ICoreValuesPatchRequest {
    id!: number;
    title!: string;
    description!: string;
    displayOrder?: number;

    constructor(data?: ICoreValuesPatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.displayOrder = _data["displayOrder"];
        }
    }

    static fromJS(data: any): CoreValuesPatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CoreValuesPatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["description"] = this.description;
        data["displayOrder"] = this.displayOrder;
        return data;
    }
}

export interface ICoreValuesPatchRequest {
    id: number;
    title: string;
    description: string;
    displayOrder?: number;
}

export class CoreValuesPostRequest implements ICoreValuesPostRequest {
    title!: string;
    description!: string;
    displayOrder?: number;

    constructor(data?: ICoreValuesPostRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.description = _data["description"];
            this.displayOrder = _data["displayOrder"];
        }
    }

    static fromJS(data: any): CoreValuesPostRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CoreValuesPostRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["description"] = this.description;
        data["displayOrder"] = this.displayOrder;
        return data;
    }
}

export interface ICoreValuesPostRequest {
    title: string;
    description: string;
    displayOrder?: number;
}

export class MissionVisionPatchRequest implements IMissionVisionPatchRequest {
    id!: number;
    missionStatement!: string;
    visionStatement!: string;

    constructor(data?: IMissionVisionPatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.missionStatement = _data["missionStatement"];
            this.visionStatement = _data["visionStatement"];
        }
    }

    static fromJS(data: any): MissionVisionPatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new MissionVisionPatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["missionStatement"] = this.missionStatement;
        data["visionStatement"] = this.visionStatement;
        return data;
    }
}

export interface IMissionVisionPatchRequest {
    id: number;
    missionStatement: string;
    visionStatement: string;
}

export class OCRCEventDetailsPatchRequest implements IOCRCEventDetailsPatchRequest {
    eventDate?: number;
    eventTime!: string;
    venueName!: string;
    eligibility!: string;
    rulesPdfUrl!: string;

    constructor(data?: IOCRCEventDetailsPatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.eventDate = _data["eventDate"];
            this.eventTime = _data["eventTime"];
            this.venueName = _data["venueName"];
            this.eligibility = _data["eligibility"];
            this.rulesPdfUrl = _data["rulesPdfUrl"];
        }
    }

    static fromJS(data: any): OCRCEventDetailsPatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new OCRCEventDetailsPatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["eventDate"] = this.eventDate;
        data["eventTime"] = this.eventTime;
        data["venueName"] = this.venueName;
        data["eligibility"] = this.eligibility;
        data["rulesPdfUrl"] = this.rulesPdfUrl;
        return data;
    }
}

export interface IOCRCEventDetailsPatchRequest {
    eventDate?: number;
    eventTime: string;
    venueName: string;
    eligibility: string;
    rulesPdfUrl: string;
}

export class OCRCEventHighlightsPatchRequest implements IOCRCEventHighlightsPatchRequest {
    id!: number;
    title!: string;
    eventYear?: number;
    description!: string;
    imageUrl!: string;
    displayOrder?: number;

    constructor(data?: IOCRCEventHighlightsPatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.eventYear = _data["eventYear"];
            this.description = _data["description"];
            this.imageUrl = _data["imageUrl"];
            this.displayOrder = _data["displayOrder"];
        }
    }

    static fromJS(data: any): OCRCEventHighlightsPatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new OCRCEventHighlightsPatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["eventYear"] = this.eventYear;
        data["description"] = this.description;
        data["imageUrl"] = this.imageUrl;
        data["displayOrder"] = this.displayOrder;
        return data;
    }
}

export interface IOCRCEventHighlightsPatchRequest {
    id: number;
    title: string;
    eventYear?: number;
    description: string;
    imageUrl: string;
    displayOrder?: number;
}

export class OCRCEventHighlightsPostRequest implements IOCRCEventHighlightsPostRequest {
    title!: string;
    eventYear?: number;
    description!: string;
    imageUrl!: string;
    displayOrder?: number;

    constructor(data?: IOCRCEventHighlightsPostRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.eventYear = _data["eventYear"];
            this.description = _data["description"];
            this.imageUrl = _data["imageUrl"];
            this.displayOrder = _data["displayOrder"];
        }
    }

    static fromJS(data: any): OCRCEventHighlightsPostRequest {
        data = typeof data === 'object' ? data : {};
        let result = new OCRCEventHighlightsPostRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["eventYear"] = this.eventYear;
        data["description"] = this.description;
        data["imageUrl"] = this.imageUrl;
        data["displayOrder"] = this.displayOrder;
        return data;
    }
}

export interface IOCRCEventHighlightsPostRequest {
    title: string;
    eventYear?: number;
    description: string;
    imageUrl: string;
    displayOrder?: number;
}

export class OCRCTimelinePatchRequest implements IOCRCTimelinePatchRequest {
    id?: number;
    timelineYear?: number;
    eventDescription!: string;
    displayOrder?: number;

    constructor(data?: IOCRCTimelinePatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.timelineYear = _data["timelineYear"];
            this.eventDescription = _data["eventDescription"];
            this.displayOrder = _data["displayOrder"];
        }
    }

    static fromJS(data: any): OCRCTimelinePatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new OCRCTimelinePatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["timelineYear"] = this.timelineYear;
        data["eventDescription"] = this.eventDescription;
        data["displayOrder"] = this.displayOrder;
        return data;
    }
}

export interface IOCRCTimelinePatchRequest {
    id?: number;
    timelineYear?: number;
    eventDescription: string;
    displayOrder?: number;
}

export class OCRCTimelinePostRequest implements IOCRCTimelinePostRequest {
    timelineYear?: number;
    eventDescription!: string;
    displayOrder?: number;

    constructor(data?: IOCRCTimelinePostRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.timelineYear = _data["timelineYear"];
            this.eventDescription = _data["eventDescription"];
            this.displayOrder = _data["displayOrder"];
        }
    }

    static fromJS(data: any): OCRCTimelinePostRequest {
        data = typeof data === 'object' ? data : {};
        let result = new OCRCTimelinePostRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["timelineYear"] = this.timelineYear;
        data["eventDescription"] = this.eventDescription;
        data["displayOrder"] = this.displayOrder;
        return data;
    }
}

export interface IOCRCTimelinePostRequest {
    timelineYear?: number;
    eventDescription: string;
    displayOrder?: number;
}

export class ServicePatchRequest implements IServicePatchRequest {
    id!: number;
    title!: string;
    shortDescription!: string;
    iconName!: string;
    displayOrder?: number;
    isActive?: boolean;

    constructor(data?: IServicePatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.shortDescription = _data["shortDescription"];
            this.iconName = _data["iconName"];
            this.displayOrder = _data["displayOrder"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): ServicePatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ServicePatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["shortDescription"] = this.shortDescription;
        data["iconName"] = this.iconName;
        data["displayOrder"] = this.displayOrder;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface IServicePatchRequest {
    id: number;
    title: string;
    shortDescription: string;
    iconName: string;
    displayOrder?: number;
    isActive?: boolean;
}

export class ServicePostRequest implements IServicePostRequest {
    title!: string;
    shortDescription!: string;
    iconName!: string;
    displayOrder?: number;
    isActive?: boolean;

    constructor(data?: IServicePostRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.shortDescription = _data["shortDescription"];
            this.iconName = _data["iconName"];
            this.displayOrder = _data["displayOrder"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): ServicePostRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ServicePostRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["shortDescription"] = this.shortDescription;
        data["iconName"] = this.iconName;
        data["displayOrder"] = this.displayOrder;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface IServicePostRequest {
    title: string;
    shortDescription: string;
    iconName: string;
    displayOrder?: number;
    isActive?: boolean;
}

export class TeamMembersPatchRequest implements ITeamMembersPatchRequest {
    id!: number;
    firstName!: string;
    lastName!: string;
    roleTitle!: string;
    bio!: string;
    profileImageUrl!: string;
    displayOrder?: number;
    isActive?: boolean;

    constructor(data?: ITeamMembersPatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.roleTitle = _data["roleTitle"];
            this.bio = _data["bio"];
            this.profileImageUrl = _data["profileImageUrl"];
            this.displayOrder = _data["displayOrder"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): TeamMembersPatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new TeamMembersPatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["roleTitle"] = this.roleTitle;
        data["bio"] = this.bio;
        data["profileImageUrl"] = this.profileImageUrl;
        data["displayOrder"] = this.displayOrder;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface ITeamMembersPatchRequest {
    id: number;
    firstName: string;
    lastName: string;
    roleTitle: string;
    bio: string;
    profileImageUrl: string;
    displayOrder?: number;
    isActive?: boolean;
}

export class TeamMembersPostRequest implements ITeamMembersPostRequest {
    firstName!: string;
    lastName!: string;
    roleTitle!: string;
    bio!: string;
    profileImageUrl!: string;
    displayOrder?: number;
    isActive?: boolean;

    constructor(data?: ITeamMembersPostRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.roleTitle = _data["roleTitle"];
            this.bio = _data["bio"];
            this.profileImageUrl = _data["profileImageUrl"];
            this.displayOrder = _data["displayOrder"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): TeamMembersPostRequest {
        data = typeof data === 'object' ? data : {};
        let result = new TeamMembersPostRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["roleTitle"] = this.roleTitle;
        data["bio"] = this.bio;
        data["profileImageUrl"] = this.profileImageUrl;
        data["displayOrder"] = this.displayOrder;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface ITeamMembersPostRequest {
    firstName: string;
    lastName: string;
    roleTitle: string;
    bio: string;
    profileImageUrl: string;
    displayOrder?: number;
    isActive?: boolean;
}

export class TestimonialPatchRequest implements ITestimonialPatchRequest {
    id!: number;
    rate!: number;
    authorName!: string;
    authorRole!: string;
    content!: string;
    isApproved?: boolean;

    constructor(data?: ITestimonialPatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.rate = _data["rate"];
            this.authorName = _data["authorName"];
            this.authorRole = _data["authorRole"];
            this.content = _data["content"];
            this.isApproved = _data["isApproved"];
        }
    }

    static fromJS(data: any): TestimonialPatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new TestimonialPatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["rate"] = this.rate;
        data["authorName"] = this.authorName;
        data["authorRole"] = this.authorRole;
        data["content"] = this.content;
        data["isApproved"] = this.isApproved;
        return data;
    }
}

export interface ITestimonialPatchRequest {
    id: number;
    rate: number;
    authorName: string;
    authorRole: string;
    content: string;
    isApproved?: boolean;
}

export class TestimonialPostRequest implements ITestimonialPostRequest {
    rate!: number;
    authorName!: string;
    authorRole!: string;
    content!: string;
    isApproved?: boolean;

    constructor(data?: ITestimonialPostRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.rate = _data["rate"];
            this.authorName = _data["authorName"];
            this.authorRole = _data["authorRole"];
            this.content = _data["content"];
            this.isApproved = _data["isApproved"];
        }
    }

    static fromJS(data: any): TestimonialPostRequest {
        data = typeof data === 'object' ? data : {};
        let result = new TestimonialPostRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["rate"] = this.rate;
        data["authorName"] = this.authorName;
        data["authorRole"] = this.authorRole;
        data["content"] = this.content;
        data["isApproved"] = this.isApproved;
        return data;
    }
}

export interface ITestimonialPostRequest {
    rate: number;
    authorName: string;
    authorRole: string;
    content: string;
    isApproved?: boolean;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}